package cn.wawi.model.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
@JsonIgnoreProperties("password")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}

	public java.lang.String getRealname() {
		return get("realname");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}

	public java.lang.String getNickname() {
		return get("nickname");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setBirthday(java.util.Date birthday) {
		set("birthday", birthday);
	}

	@JsonFormat(pattern="yyyy-MM-dd")
	public java.util.Date getBirthday() {
		return get("birthday");
	}

	public void setGeneder(java.lang.String geneder) {
		set("geneder", geneder);
	}

	public java.lang.String getGeneder() {
		return get("geneder");
	}

	public void setRegTime(java.util.Date regTime) {
		set("reg_time", regTime);
	}

	public java.util.Date getRegTime() {
		return getDate("reg_time");
	}

	public void setDeptId(java.lang.Integer deptId) {
		set("dept_id", deptId);
	}

	public java.lang.Integer getDeptId() {
		return get("dept_id");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
