package cn.wawi.model.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDepartment<M extends BaseDepartment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDeptName(java.lang.String deptName) {
		set("dept_name", deptName);
	}

	public java.lang.String getDeptName() {
		return get("dept_name");
	}

	public void setDeptAddress(java.lang.String deptAddress) {
		set("dept_address", deptAddress);
	}

	public java.lang.String getDeptAddress() {
		return get("dept_address");
	}

	public void setDeptPhone(java.lang.String deptPhone) {
		set("dept_phone", deptPhone);
	}

	public java.lang.String getDeptPhone() {
		return get("dept_phone");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setParentId(java.lang.Integer parentId) {
		set("parent_id", parentId);
	}

	public java.lang.Integer getParentId() {
		return get("parent_id");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
