package cn.wawi.model.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAttach<M extends BaseAttach<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setAttachUrl(java.lang.String attachUrl) {
		set("attach_url", attachUrl);
	}

	public java.lang.String getAttachUrl() {
		return get("attach_url");
	}

	public void setRelationId(java.lang.Integer relationId) {
		set("relation_id", relationId);
	}

	public java.lang.Integer getRelationId() {
		return get("relation_id");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}

	public java.lang.String getType() {
		return get("type");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	@JsonFormat(pattern="yyyy-MM-dd hh:mm:ss")
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
