package cn.wawi.model.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setRoleName(java.lang.String roleName) {
		set("role_name", roleName);
	}

	public java.lang.String getRoleName() {
		return get("role_name");
	}

	public void setRoleCode(java.lang.String roleCode) {
		set("role_code", roleCode);
	}

	public java.lang.String getRoleCode() {
		return get("role_code");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
