package cn.wawi.model.sys.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLog<M extends BaseLog<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setIp(java.lang.String ip) {
		set("ip", ip);
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public void setOs(java.lang.String os) {
		set("os", os);
	}

	public java.lang.String getOs() {
		return get("os");
	}

	public void setBrowser(java.lang.String browser) {
		set("browser", browser);
	}

	public java.lang.String getBrowser() {
		return get("browser");
	}

	public void setOptUser(java.lang.String optUser) {
		set("opt_user", optUser);
	}

	public java.lang.String getOptUser() {
		return get("opt_user");
	}

	public void setRealname(java.lang.String realname) {
		set("realname", realname);
	}

	public java.lang.String getRealname() {
		return get("realname");
	}

	public void setIsSuccess(java.lang.String isSuccess) {
		set("is_success", isSuccess);
	}

	public java.lang.String getIsSuccess() {
		return get("is_success");
	}

	public void setReqParam(java.lang.String reqParam) {
		set("req_param", reqParam);
	}

	public java.lang.String getReqParam() {
		return get("req_param");
	}

	public void setReqUrl(java.lang.String reqUrl) {
		set("req_url", reqUrl);
	}

	public java.lang.String getReqUrl() {
		return get("req_url");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
	}
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
