package open.weixin;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

import cn.wawi.model.sys.Area;
import cn.wawi.model.sys.Attach;
import cn.wawi.model.sys.Department;
import cn.wawi.model.sys.Dictionary;
import cn.wawi.model.sys.Log;
import cn.wawi.model.sys.Resources;
import cn.wawi.model.sys.Role;
import cn.wawi.model.sys.User;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("sys_area", "id", Area.class);
		arp.addMapping("sys_attach", "id", Attach.class);
		arp.addMapping("sys_department", "id", Department.class);
		arp.addMapping("sys_dictionary", "id", Dictionary.class);
		arp.addMapping("sys_log", "id", Log.class);
		arp.addMapping("sys_resources", "id", Resources.class);
		arp.addMapping("sys_role", "id", Role.class);
		arp.addMapping("sys_user", "id", User.class);
	}
}

