package cn.wawi.model.sys;

import cn.wawi.model.sys.base.BaseAttach;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Attach extends BaseAttach<Attach> {
	public static final Attach dao = new Attach();
}
