package cn.wawi.model.sys;

import java.util.Date;

import cn.wawi.model.sys.base.BaseDepartment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Department extends BaseDepartment<Department> {
	public static final Department dao = new Department();
	public Department(){
		this.setCreateTime(new Date());
	}
}
