package cn.wawi.model.sys;

import cn.wawi.model.sys.base.BaseDictionary;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dictionary extends BaseDictionary<Dictionary> {
	public static final Dictionary dao = new Dictionary();

}
