package cn.wawi.model.sys;

import java.util.Date;

import cn.wawi.model.sys.base.BaseLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Log extends BaseLog<Log> {
	public static final Log dao = new Log();
	public Log(){
		this.setCreateTime(new Date());
	}
}
