package cn.wawi.model.sys;

import java.util.Date;
import java.util.List;
import cn.wawi.model.sys.base.BaseRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseRole<Role> {
	public static final Role dao = new Role();
	public Role(){
		this.setCreateTime(new Date());
	}
	
	public List<Role> getUserRole(int userId){
		return find("SELECT  r.*  FROM sys_role r LEFT JOIN sys_user_role ur ON  r.id=ur.role_id WHERE ur.user_id=?",userId);
	}
	
}
