package cn.wawi.model.sys;

import java.util.Date;

import com.jfinal.kit.HashKit;

import cn.wawi.model.sys.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();
	
	public User(){
		this.setRegTime(new Date());
	}

	/**
	 *  用户登录
	 */
	public User login(String username,String password){
		password=HashKit.md5(HashKit.sha1(username+password));
		return findFirst("select * from sys_user where username=? and password=?",new Object[]{username,password});
	}
	public static void main(String[] args) {
		System.out.println(HashKit.md5(HashKit.sha1("test123456")));
	}
}
